### ISSUE TITLE
Error when parsing type declaration in 0.4.0

### ISSUE THREAD

**Issue by tmlbl** [JuliaLang/JuliaParser.jl#28] opened 2015-10-25 17:35 UTC
````julia
julia> ts = Lexer.TokenStream("""
       type Foo
           name::AbstractString
       end
       """)
JuliaParser.Lexer.TokenStream(IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=38, maxsize=Inf, ptr=1, mark=-1),1,nothing,nothing,false,false,"")

julia> Lexer.next_token(ts)
:type

julia> Lexer.next_token(ts)
:Foo

julia> Lexer.next_token(ts)
'\n'

julia> Lexer.next_token(ts)
:name

julia> Lexer.next_token(ts)
ERROR: cannot resize array with shared data
 in push! at ./array.jl:433
 in read_operator at /Users/tim/.julia/v0.4/JuliaParser/src/lexer.jl:368
 in next_token at /Users/tim/.julia/v0.4/JuliaParser/src/lexer.jl:752
 in next_token at /Users/tim/.julia/v0.4/JuliaParser/src/lexer.jl:768
````

**Comment by hustf** [comment] 2015-10-25 17:58
This may be fixed in the 'master' version. Try Pkg.checkout("JuliaParser).
If this works, and the 'master' version is tagged as a release in the future, you can Pkg.free("JuliaParser") again.

**Comment by Keno** [comment] 2016-01-19 01:18
I cannot reproduce this, so I assume it's fixed.

**Closed by Keno** 2016-01-19 01:18 UTC
